### PR TITLE
Embedded Messages

### PR DESCRIPTION
**Pull request by wattsit**
getfilm command now returns an embedded message, ready for API integration.

### CODE REVIEW

**Comment by whitew1994WW** [comment]
Is this now deprecated with the other PR @wattsit?

**Comment by wattsit** [comment]
Yeah it is. Not sure on the best practice in this situation.

**Comment by whitew1994WW** [comment]
Thats alright. Best practice is that you push to a separate branch until the change is stable, and then you create a pull request into the master/staging branch. If you then need to make changes to that pull request you should be able to push to the branch with an open pull request and it will auto-update the pull request.

If this one is no longer needed then you can delete it :)

**Comment by wattsit** [comment]
Branch deprecated.

**Pull request closed without merging**
